### ISSUE TITLE
Problema de indentación

### ISSUE THREAD

**Issue by sponja23** [IgnacioPardo/TD1_UTDT#1]
El archivo [TD1_UTDT/peculiar.py](https://github.com/IgnacioPardo/TD1_UTDT/blob/main/TP1%20TD/peculiar.py) tiene reglas de indentación inconsistentes: a veces usa `TAB` y a veces 2 espacios. Si alguien tiene un editor de texto que muestra los `TAB`s como 4 espacios, se ve raro:

![Screenshot from 2021-04-16 23-42-38](https://user-images.githubusercontent.com/10713113/115099622-7e763780-9f0d-11eb-8f06-1da43ba73ccd.png)

**Comment by sponja23** [comment]
Se me ocurre que esto se podría solucionar con el formateador [Black](https://github.com/psf/black), que además sigue los estándares de la [PEP 8](https://www.python.org/dev/peps/pep-0008/).

**Comment by IgnacioPardo** [comment]
Lo formateo con black y pusheo los cambios. Resuelto en https://github.com/IgnacioPardo/TD1_UTDT/commit/9dfa4918ff4bf0bca33cbcb087760b0aea1ce9d2.
